name: Publish NuGet package

on:
  push:
    tags:
      - '*.*.*'

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Extract version from tag
        id: version
        run: |
          echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      - name: Build project
        run: dotnet build ./LusiUtilsLibrary/LusiUtilsLibrary.csproj -c Release
      - name: Pack NuGet package
        run: |
          dotnet pack ./LusiUtilsLibrary/LusiUtilsLibrary.csproj \
            -c Release \
            -p:PackageVersion=${{ steps.version.outputs.version }}
      - name: Publish to GitHub Packages
        run: >
          dotnet nuget push ./LusiUtilsLibrary/bin/Release/*.nupkg
            --api-key ${{ secrets.GITHUB_TOKEN }}
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
